name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify-codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/go-mod
            vendor
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Vendor dependencies
        run: make vendor

      - name: Verify codegen & docs
        run: make verify-codegen
