# .github/workflows/verify-codegen.yml
name: Verify codegen

permissions: {}

on:
  pull_request:
    branches:
      - 'main'
      - 'release*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  required:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Fetch Kyverno APIs into GOPATH shim
        run: |
          # our Makefile will symlink PWD into .gopath/src/github.com/kyverno/reports-server
          mkdir -p .gopath/src/github.com/kyverno
          git clone https://github.com/kyverno/kyverno.git .gopath/src/github.com/kyverno/kyverno

      - name: Verify codegen
        # disable modules so code-generator actually reads from .gopath
        env:
          GO111MODULE: off
          GOPATH:     ${{ github.workspace }}/.gopath
        run: |
          set -e
          make verify-codegen
