# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Tests

permissions: {}

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOPRIVATE: github.com/nirmata
  GH_DEP_USERNAME: ${{secrets.DEPLOYMENT_USERNAME}}
  GH_DEP_PAT: ${{secrets.DEPLOYMENT_PAT}}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum
    - run: git config --global url.https://$GH_DEP_USERNAME:$GH_DEP_PAT@github.com/.insteadOf https://github.com/
    - name: Run tests
      run: |
        set -e
        make tests
  required:
    needs:
    - unit-tests
    runs-on: ubuntu-latest
    steps:
    - run: echo "Required jobs success!"